const POP_FILE = 'pop.wav';
const CRASH_FILE = 'crash.wav';
const TADA_FILE = 'tada.wav';
const WAH_FILE = 'wahwah.wav';
const BKGND_FILE = 'bkgnd-long.wav';
const PLAY_FILE = 'play-long.wav';
const WHISTLE_FILE = 'whistle.wav';
const PAUSE_INTERVAL = 3.0; // pause in secs when a point is scored
const MAX_NET_WAIT = Duration(seconds: 10); // assume opponent disconnected
const HIT_WAIT = Duration(milliseconds: 60); // guard repeated hits due to lag
